### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#11]
Could you please add light mode? I am not used to the dark.
`button(onclick="halfmoon.toggleDarkMode()")` should be fairly easy.

**Comment by ghost** [comment]
https://github.com/RiversideRocks/web-riverside/pull/12

**Comment by trentwiles** [comment]
https://github.com/RiversideRocks/web-riverside/blob/master/src/mode.js

We are working on this now.

**Comment by ghost** [comment]
Ah, cool!
Shall ya' add a privacy policy?

**Comment by trentwiles** [comment]
I belive we already have one.

**Comment by ghost** [comment]
i don't actually remember, could you link it?

**Comment by dispherical** [comment]
He actually does have a privacy policy, he just didn't move it over to the new website yet.

**Comment by trentwiles** [comment]
You can check out our in progress legal docs here:

https://riverside.rocks/about/legal/

**Comment by trentwiles** [comment]
We are having a few issues with the UI, its still under construction.

**Comment by dispherical** [comment]
Should this issue be closed?

**Comment by ghost** [comment]
i don't think so

**Comment by trentwiles** [comment]
We don't have this in our roadmap at the moment, if you want light mode, run `halfmoon.toggleDarkMode()` in the console.
