### ISSUE TITLE
heck yes

### ISSUE THREAD

**Issue by oldalt** [RiversideRocks/web-riverside#21]
HECK YES THERE IS A DASHBOARD THAT WORKS WITH GITHUB OAUTH YES YES YES

**Comment by trentwiles** [comment]
Thanks! GitHub seems to be the best option for most.

**Comment by ghost** [comment]
naah i am not giving away my github account permissions for this 😂

**Comment by oldalt** [comment]
why not 😳
________________________________

**Comment by ghost** [comment]
i donut wanna give away my account to a site with such breaches.
You should've been in the chat

**Comment by oldalt** [comment]
GitHub OAuth doesn't share the password. And besides the account is worthless anyways. Plus it can change things about, nor your repos

**Comment by trentwiles** [comment]
> 
> 
> i donut wanna give away my account to a site with such breaches.

What do you mean?

**Comment by ghost** [comment]
> GitHub OAuth doesn't share the password. And besides the account is worthless anyways. Plus it can change things about, nor your repos

I know it doesn't share passwords, and how is my account worthless?



> > i donut wanna give away my account to a site with such breaches.
> 
> What do you mean?

Weren't you in the chat?

**Comment by trentwiles** [comment]
It was a small bug that was patched in less than an hour.

**Comment by ghost** [comment]
ik but there may be bugs like it soon

**Comment by trentwiles** [comment]
Probably not, I do a ton of security checks. I'm also working on the contact form so users can contact me about security issues!

**Comment by ghost** [comment]
i can help you do a contact form.

**Comment by trentwiles** [comment]
Ok, you can always make a pull request.

**Comment by ghost** [comment]
here's how it should work:
Everytime someone submits a message, you get an email:
The subject is:
```(Contact form) SUBJECT```
And the message inside is:
```
New message from user USERNAME at HOUR:MINUTE

MESSAGE

Metadata:
username: USERNAME
email: EMAIL
IP: IP
```

can you make another email where you receive the messages from the contact form, so moderators can look trough them?

**Comment by oldalt** [comment]
No one would then do that.
