### ISSUE TITLE
Messages bug

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#27]
Do not believe anything that gets sent on the tucker account, i am not sending those messages.
Ask me here if i send a message just to be sure.

**Comment by ghost** [comment]
Also if anything wierd gets posted on BiblitoecaOvidiu, still not me.
Ask me here!

**Comment by ghost** [comment]
It was me all the time, some may be others but i dont know :D

**Comment by trentwiles** [comment]
Fixed on 276cc4ef864ed424037c3180ef95f6d50318f381

**Comment by ghost** [comment]
unpin this

**Comment by trentwiles** [comment]
sure but I fixed it! lets go!
