### ISSUE TITLE
[CRITICAL] Banning Not Working

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#28]
**Attention!**
There's an issue going around that you cannot get banned. Your username gets changed to "tucker" and you can log out and in back to reset your username.
This may be considered a security risk!

**Comment by ghost** [comment]
@RiversideRocks add the bug label
https://github.com/RiversideRocks/web-riverside/labels/bug

**Comment by greasezone** [comment]
this is bad

**Comment by trentwiles** [comment]
The "tucker" bug has been patched.

**Comment by ghost** [comment]
Seriously? Can you ban BibliotecaOvidiu?
