### ISSUE TITLE
DDoS Protection

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#41]
Do you want me to try and open a bunch of tabs on your website, like sending a lot of requests, for testing?

**Comment by LankyBox01** [comment]
I mean, not actually a real DDoS, that's illegal -- i am refering to just opening the website and duplicating the tab very quick

**Comment by trentwiles** [comment]
You can try whatever you want, just review the hacking policy at /about/hacking

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
You're giving me permission to perform this?

**Comment by trentwiles** [comment]
Yes, I am.

**Comment by ghost** [comment]
ok, just wait

**Comment by ghost** [comment]
it's loading really hard, do you receive any requests?

**Comment by trentwiles** [comment]
yep I think we got around 100 requests

**Comment by dispherical** [comment]
Opening many tabs at once is not a DDoS, more like a DoS

**Comment by ghost** [comment]
LOL! So how do you prevent that?

**Comment by dispherical** [comment]
Cloudflare (D)DoS protection?

**Comment by ghost** [comment]
> Opening many tabs at once is not a DDoS, more like a DoS

Not really, i use a thing code-alt made that opens a lot of iframes on the click of a button

**Comment by trentwiles** [comment]
DDoSing or DoS is sending a good deal of requests, 100 requests is not that many.

**Comment by dispherical** [comment]
DDoS is multiple computers. DoS is only one computer.

**Comment by ghost** [comment]
Ohoho, wait a few seconds.

**Comment by dispherical** [comment]
Distributed Denial of Service attack. Distributed meaning more than one computer. You only used one computer.
Edit: Opening multiple tabs on one computer is only one computer :/

**Comment by ghost** [comment]
This isn't a DoS nor a DDoS at all.
It's just opening a bunch of tabs (or iframes, whatever you like to call it)

**Comment by trentwiles** [comment]
Ok, so what are you trying to do?

**Comment by ghost** [comment]
Testing if it can go down
How many requests are ya receiving?

**Comment by Misly16** [comment]
opening even 1000 tabs wont affect a site.

**Comment by trentwiles** [comment]
You would have to send around 30,000 requests a minute to take it down. You are sending 60.

**Comment by ghost** [comment]
XD
Ok, lemme just pull out my secret weapon...
2 TABS!

**Comment by dispherical** [comment]
It's actually hard to make a server to go down (unless it's a unboosted Glitch project or like a Raspberry Pi 0w w/o Cloudflare.)

**Comment by ghost** [comment]
Yeah, really.

**Comment by ghost** [comment]
River, Maybe add a feature to make the site go down for a few minutes when the website is receiving too many reqs

**Comment by trentwiles** [comment]
Erm, why???

**Comment by ghost** [comment]
To protect yourself from DDoS?

**Comment by dispherical** [comment]
> Cloudflare (D)DoS protection?

**Comment by trentwiles** [comment]
I already use that and it works.

**Comment by ghost** [comment]
I'm literally opening 100 tabs a minute.. im lagging so hard XD

**Comment by LankyBox01** [comment]
Lemme try something, can you add this to the homepage:
```
<!-- hitwebcounter Code START -->
<a href="https://www.hitwebcounter.com" target="_blank">
<img src="https://hitwebcounter.com/counter/counter.php?page=7706657&style=0036&nbdigits=6&type=page&initCount=2000" title="Total Website Hits" Alt="Web Hits"   border="0" /></a>
```
Do not modify it tho!

**Comment by trentwiles** [comment]
![](https://riverside.rocks/assets/serve/production/app/5fa6e9a111d19.png)

I have a visit counter on the homepage.

**Comment by ghost** [comment]
Could you delete this issue please?

**Comment by ghost** [comment]
Nvm do not delete it

**Comment by ghost** [comment]
Huh, the website isn't loading anymore.
I guess i kinda overloaded it

**Comment by ghost** [comment]
wait it's back

**Comment by ghost** [comment]
Delete this

**Comment by ghost** [comment]
what? why did you reopen?
