### ISSUE TITLE
Log-in error

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#43]
If i try to log in, i do not get prompted to the dashboard -- instead, a text appears saying "Hello BibliotecaOvidiu, your ID is" and a lot of numbers.

**Comment by trentwiles** [comment]
What browser are you using?

**Comment by ghost** [comment]
Lemme get the version

**Comment by ghost** [comment]
Google Chrome 86

**Comment by ghost** [comment]
maybe it's a problem with the recent commits, not working!

**Comment by ghost** [comment]
btw, the url changes to https://riverside.rocks/oauth/github?code=[SOME_SECRET_CODE]

**Comment by trentwiles** [comment]
Can you confirm this is still happening?

**Comment by ghost** [comment]
yes, it's still happening.

**Comment by trentwiles** [comment]
Patched, if you have any more issues, reopen this issue.
