### ISSUE TITLE
response

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#44]
Patched, if you have any more issues, reopen this issue.

_Originally posted by @RiversideRocks in https://github.com/RiversideRocks/web-riverside/issues/43#issuecomment-724129121_

I cannot re-open issues closed by those with write access, just saying.

**Comment by ghost** [comment]
btw, when i try sending a message in chat, the input value is set to _"This account is not able to send messages."_

**Comment by trentwiles** [comment]
Patched in 504376e41f1285562e772cdff2de8d214ca18c1c

**Comment by trentwiles** [comment]
Sign back in for the patch to take effect.
