### ISSUE TITLE
Make /app image more visible

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#53]
The image in https://riverside.rocks/app/ looks like it's the actual chat, not just a picture - i say you make it more obvious it's a picture

**Comment by trentwiles** [comment]
Good point, thanks!

**Comment by trentwiles** [comment]
See commit c1a22d76ae09eac00468377224f5f5b24cbfd2d7. Thanks for the idea!

**Comment by ghost** [comment]
No problem :P

**Comment by ghost** [comment]
You can also try a slideshow:
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_slideshow
