### ISSUE TITLE
Your account is blocked

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#59]
```
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading">Account block</h4>
  Your account was blocked from sending messages to the chat.
</div>
```

Halfmoon design for an "account blocked" thing

**Comment by trentwiles** [comment]
We already do have a few alerts for bans and errors, have a look at those:

https://github.com/RiversideRocks/web-riverside/blob/master/src/v1/client.js#L53
