### ISSUE TITLE
Forum Suggestions

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#6]
Are you gonna build a forum by itself with HTML and CSS? Or are you gonna use a Bulletin Board?
I have gathered a list of choices:

- [NodeBB](https://nodebb.org/)
- [MyBB](https://mybb.com/)
- [DjangoBB](http://djangobb.org/)
- [FluxBB](https://fluxbb.org/)

**Comment by trentwiles** [comment]
Hey,

So I am planning on coding my own forum like the one from the last site.

**Comment by ghost** [comment]
oh, cool.
