### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#60]
Oof, almost done with the design!
```
.page-wrapper.with-sidebar
  .sidebar
    .sidebar-menu
      a.sidebar-brand(href='https://riverside.rocks/' rel='noopener noreferrer' target='_blank') Riverside Rocks
      // Sidebar links and titles
      h5.sidebar-title Channels
      .sidebar-divider
        br
        button.btn.btn-primary(type='button') #general
        br
        br
        button.btn(type='button') #YouTube
        br
        br
        button.btn(type='button') #Technology
  .content-wrapper
    h2(style='padding-left:10px;') #general
    .border
      strong(style='font-size:15px;') LankyBox01: 
      span(style='font-size:15px;') Henlo
    .border
      strong(style='font-size:15px;') RiversideRocks: 
      span(style='font-size:15px;') Henlo
    .border
      strong(style='font-size:15px;') Eddiestech: 
      span(style='font-size:15px;') Nice design!
    .border
      strong(style='font-size:15px;') Code-alt: 
      span(style='font-size:15px;') Henlo
    .border
      strong(style='font-size:15px;') LankyBox01: 
      span(style='font-size:15px;') Yeet boi
```

**Comment by trentwiles** [comment]
You know, I like it. I'm going to make a few quick tweaks, you can see the results here:

https://riverside.rocks/app/beta

**Comment by trentwiles** [comment]
https://riverside.rocks/assets/serve/production/app/5fb698d33148c.mp4

^ New design preview

**Comment by ghost** [comment]
Dude that's soo cooool!
I'll add another sidebar on the right where it shows all the members, moderators, admins, etc.

**Comment by trentwiles** [comment]
That would be a good idea. Maybe on the bottom?

**Comment by trentwiles** [comment]
I'm having my discord server vote on the design, later I will announce the results.

**Comment by ghost** [comment]
> I'm having my discord server vote on the design, later I will announce the results.

Cool idea!

> That would be a good idea. Maybe on the bottom?

Well, not sure how that would fit since i will add the input at the bottom

**Comment by trentwiles** [comment]
I just don't want it to get too crowded. I also don't want to use discord's design too much.

**Comment by ghost** [comment]
Yeah, sure. I'll see what i can do!

**Comment by ghost** [comment]
I have an idea
What if you make "Toggle dark mode" look like a button, and make it align to the right?

**Comment by trentwiles** [comment]
What do you mean?

**Comment by ghost** [comment]
Wait, lemme make a mockup

**Comment by ghost** [comment]
![newmockup](https://user-images.githubusercontent.com/66025173/99693547-289f7f80-2a94-11eb-9745-13f27a29b7b3.png)
Like this, look at the navbar

**Comment by trentwiles** [comment]
Hmm, I suppose. I do like it where it is right now.

**Comment by ghost** [comment]
For me it's a little.. out of place

**Comment by trentwiles** [comment]
Where it is now?

**Comment by trentwiles** [comment]
Also, would you want me to set up a forum?

**Comment by LankyBox01** [comment]
Yes.

**Comment by ghost** [comment]
Isn't the chat already a forum?

**Comment by ghost** [comment]
"kind-of"

**Comment by trentwiles** [comment]
A forum would make things much more neat. Let me set one up.

**Comment by ghost** [comment]
I mean

**Comment by ghost** [comment]
We cannot have a chat and a forum at the same time, right?

**Comment by ghost** [comment]
I think we should use the new design we're making as a forum, what do you think?

**Comment by trentwiles** [comment]
Let move this to a chat on the site, its a bit tricky to chat here.

**Comment by trentwiles** [comment]
https://riverside.rocks/app/channels/general

**Comment by trentwiles** [comment]
Something went wrong, reload.

**Comment by ghost** [comment]
help

**Comment by ghost** [comment]
it's just saying "undefined"

**Comment by trentwiles** [comment]
hard refresh, issue in the code base

**Comment by ghost** [comment]
done, works now!

**Comment by ghost** [comment]
reopen pls
`input.form-control(type='text' placeholder='Text input')`

**Comment by ghost** [comment]
ty

**Comment by code-alt** [comment]
I'm gonna make my own Discord like theme, and convert it into pug since, hey, your gonna have a forum and chat. I'll stick with halfmoon and fire an event anytime you change the theme and change it to the white/dark palette.

**Comment by ghost** [comment]
@code-alt try to make it different from discord. Riverside said:

> I also don't want to use discord's design too much.

**Comment by code-alt** [comment]
Oh, then, sure, yeah. I will do that. And add some drop down lists for channels and that stuff

**Comment by ghost** [comment]
Actually, you can just contribute to the design i made - i'm done with it currently.
And we're also saving more time!

**Comment by trentwiles** [comment]
How is the design looking? I can't wait.

**Comment by ghost** [comment]
@code-alt

**Comment by code-alt** [comment]
I personally don't like it. I'm gonna make my own.

**Comment by trentwiles** [comment]
Ok, may the best design win.

**Comment by code-alt** [comment]
Alrighty, let's do it!

It is a bit harder to update (by adding a few seconds, but hey...) but here is what I'm thinking

https://remarkable-caring-target.glitch.me/

**Comment by ghost** [comment]
Dude yours is wayyy better!
Tough why was i banned? XD

**Comment by trentwiles** [comment]
What do you mean?

**Comment by ghost** [comment]
In the design he made, he included "LankyBox01 was banned".
I think he included it just as an example, XD

**Comment by trentwiles** [comment]
@LankyBox01 any update on your design?

**Comment by ghost** [comment]
Nope.

**Comment by code-alt** [comment]
I will possibly add banning.

**Comment by ghost** [comment]
Make an admin panel!

**Comment by code-alt** [comment]
This was my original plan btw:

![image](https://user-images.githubusercontent.com/74145728/99921357-77952100-2cef-11eb-875d-84560f0df8c7.png)

**Comment by ghost** [comment]
Dude! That's like so cool! I have an idea - why don't we merge all of our designs together?

**Comment by ghost** [comment]
I am working on it...

**Comment by trentwiles** [comment]
Nice!

**Comment by code-alt** [comment]
WDYM by merging designs? They are completely different!

**Comment by ghost** [comment]
You add assets from one design to another and make their style to look like the other

**Comment by code-alt** [comment]
Why did you close this?

**Comment by ghost** [comment]
Oh i didn't mean to close it!

**Comment by code-alt** [comment]
Seems like LankyBox isn't using GitHub anymore. And @ghost's pfp is a bit creepy at first.

**Comment by trentwiles** [comment]
OP deleted their account, closing the issue.

**Comment by LankyBox01** [comment]
> Seems like LankyBox isn't using GitHub anymore. And @ghost's pfp is a bit creepy at first.

lmao you got scared?

> OP deleted their account, closing the issue.

And i created another. Re-open the issue!
