### ISSUE TITLE
Apparently..

### ISSUE THREAD

**Issue by ghost** [RiversideRocks/web-riverside#68]
Every time i try to create a new file, i get a 404.
So i will be posting my idea here: COLORFUL EASTER EGG

All you have to do is type out "River", not in a box or someting - just type it out normally, and then this should happen:
`(function(){
  var all = document.getElementsByTagName("*");
  for (var i=0, max=all.length; i < max; i++) {
    all[i].style.backgroundColor ='#'+Math.floor(Math.random()*16777215).toString(16);
  }
})();`

Go ahead and try it, in the console!

**Comment by trentwiles** [comment]
If you want to make a new file you can always try this link:

https://github.com/RiversideRocks/web-riverside/new/master

**Comment by ghost** [comment]
That is where i am getting the 404

**Comment by trentwiles** [comment]
Maybe fork it?
